name: Bug Report
description: Report a bug in Codimir I/O
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
